/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logical;

import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import mathinterpreter.*;

/**
 *
 * @author eriko
 */

public class LogicPane extends javax.swing.JPanel {

    /**
     * Creates new form LogicPane
     */
    MainFrame _main;
    LogicEquation equation;
    String format;
    String name;
    public LogicPane(String name, MainFrame m) {
        equation = new LogicEquation();
        _main = m;
        this.name = name;
        initComponents();
        jPanel1.setLayout(new GridLayout(0,1)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jTextField1.setToolTipText("Equation");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        _main.deleteTab(name);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        equation.setEquation(jTextField1.getText());
        preformOperations();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            equation.setEquation(jTextField1.getText());
            preformOperations();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private String getHeading(ArrayList<String> variables){
        return equation.toString()+"\n"+String.format(format, variables.toArray())+"Outcome\n";
    }
    
    private String formatRow(String states, String outcome){
        ArrayList<String> formatTargets = new ArrayList();
        for(char c: states.toCharArray())
            formatTargets.add(String.valueOf(c=='0'));
        return String.format(format, formatTargets.toArray())+outcome+"\n";
    }
    
    private void setFormat(ArrayList<String> variables){
        format = new String();
        variables.forEach(x->{format+="%-7s";});
        format+=" : ";
    }
    
    private void preformOperations(){
        ArrayList<String> variables = getVariables();
        setFormat(variables);
        String result = getHeading(variables);
        for(String states: getBinaryOutput(variables.size())){
            Map arguments = new HashMap();
            variables.forEach(x->arguments.put(x, states.charAt(variables.indexOf(x))=='0'));
            try{result += formatRow(states,equation.f(arguments));}
            catch(Exception e){System.out.println(e);return;}                
        }
        jTextArea1.setText(result);
    }
    
    private ArrayList<String> getVariables(){
        Set<String> vars = new HashSet();
        for(String part: (ArrayList<String>)equation.getParsedEquation())
            if(equation.variables.contains(part))
                vars.add(part);
        return new ArrayList(vars);
    }
    
    public ArrayList<String> getBinaryOutput(int val)
    {
        ArrayList<String> temp = new ArrayList();
        int max = (int)Math.pow(2,val);  
        for (int i = 0; i < max; i++)
            temp.add(String.format("%"+val+"s", Integer.toBinaryString(i)).replaceAll(" ", "0"));
        return  temp;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
