/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logical;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author eriko
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogicFrame
     */
    ArrayList<Entry<String,JPanel>> tabs;
    static boolean toggle = true;
    public MainFrame() {
        initComponents();
        tabs = new ArrayList();
        createTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logical");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("True/False");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 469, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        createTab();
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        toggle = !toggle;
        if(toggle)
            jButton2.setText("True/False");
        else
            jButton2.setText("   1   /   0    ");
        for(Entry<String,JPanel> entry: tabs)
            ((LogicPane)entry.entry).updateView();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void createTab(){
        String name = getAvailableChar();
        JPanel pane = new LogicPane(name,this);
        tabs.add(new Entry(name,pane));
        jTabbedPane1.addTab(name, pane);
    }
    
    public void deleteTab(String name){
        tabs.removeIf(x->x.key.equals(name));
        jTabbedPane1.remove(jTabbedPane1.indexOfTab(name));
    }
    
    public void deleteTab(int id){
        deleteTab(jTabbedPane1.getTitleAt(id));
    }
    
    private String getAvailableChar()
    {
        String result = "";
        int cur = tabs.size();
        ArrayList alphabet = new ArrayList();
        for (char c = 'A'; c <= 'Z'; ++c)
            alphabet.add(c);
        do{
            result = alphabet.get(cur%26)+result;
            cur = Math.floorDiv(cur, 26)-1;
        }while(cur>=0);
        return result;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}

class Entry<K,E>{
    K key;
    E entry;
    public Entry(K key, E entry){
        this.key = key;
        this.entry = entry;
    }
}
