/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logical;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author eriko
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogicFrame
     */
    ArrayList<Entry<String,JPanel>> tabs;
    public MainFrame() {
        initComponents();
        tabs = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logical");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 558, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(2, 2, 2)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = getAvailableChar();
        JPanel pane = new LogicPane(name,jTabbedPane1.getTabCount(),this);
        tabs.add(new Entry(name,pane));
        jTabbedPane1.addTab(name, pane);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void deleteTab(String name){
        tabs.removeIf(x->x.key.equals(name));
        jTabbedPane1.remove(jTabbedPane1.indexOfTab(name));
    }
    
    public void deleteTab(int id){
        deleteTab(jTabbedPane1.getTitleAt(id));
    }
    
    private String getAvailableChar()
    {
        for(int count = 0;count<5; count++)
        {
            String name = nameHelper("",count);
            boolean contains = false;
            for(Entry e: tabs)
                if(e.key.equals(name))
                    contains = true;
            if(!contains&&!name.isEmpty())
                return name;
        }
        return "...";
    }
    
    private String nameHelper(String base,int depth)
    {
        if (depth>0)
        {
            for (char c = 'A'; c <= 'Z'; ++c)
            {
                String name = nameHelper(base+c,depth-1);
                boolean contains = false;
                for(Entry e: tabs)
                    if(e.key.equals(name))
                        contains = true;
                if(!contains&&!name.isEmpty())
                    return name;
            }
        }
        return base;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}

class Entry<K,E>{
    K key;
    E entry;
    public Entry(K key, E entry){
        this.key = key;
        this.entry = entry;
    }
}
